name: "Prepare"
description: "Installs dependencies and sets up environment"

runs:
  using: "composite"
  steps:
    - name: "Istall Node"
      uses: "actions/setup-node@v4"
      with:
        node-version: 20

    - name: "Install Node modules"
      run: "yarn"
      shell: bash
